"""Explicit `record(...)` write API — Style A from design.md §D2.

Service-layer mutations call `await audit.record(db, ...)` inside their open
transaction. Defaults `actor`, `intent_hash`, and `intent_metadata` come from
the request contextvars set by `AuditContextMiddleware`. The redaction step
runs on `diff` before insert per ADR-010 amendment.
"""

from __future__ import annotations

import json
from collections.abc import Iterable
from typing import Any, Literal
from uuid import UUID

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from fastsaas.audit.context import actor_var, intent_var
from fastsaas.audit.models import AuditLog
from fastsaas.audit.redact import redact
from fastsaas.identity.schemas import CurrentActor

AuditAction = Literal["create", "update", "delete", "restore"]


class MissingActorError(RuntimeError):
    """Raised when `record(...)` is called outside a request context and no
    `actor=` is passed. Audit rows REQUIRE a non-null actor (FK to actors.id);
    silently dropping the write would create a coverage gap."""


class MissingIntentError(RuntimeError):
    """Raised when `record(...)` is called without `intent_var` set and no
    `intent_hash=` is passed."""


def _resolve_actor(actor: CurrentActor | None, *, where: str) -> CurrentActor:
    resolved = actor if actor is not None else actor_var.get()
    if resolved is None:
        raise MissingActorError(
            f"{where} called without actor and actor_var is unset; "
            "set actor= explicitly or use set_audit_context(...)"
        )
    return resolved


def _resolve_intent(
    intent_hash: str | None, *, where: str
) -> tuple[str, dict[str, Any]]:
    if intent_hash is not None:
        return intent_hash, {}
    intent = intent_var.get()
    if intent is None:
        raise MissingIntentError(
            f"{where} called without intent_hash and intent_var is unset"
        )
    return intent.intent_hash, dict(intent.intent_metadata)


def _build_metadata(
    base: dict[str, Any],
    *,
    extra: dict[str, Any] | None,
    organisation_id: UUID | None,
) -> dict[str, Any]:
    """Merge caller-provided metadata onto the request defaults and auto-stamp
    `org_id` from `organisation_id` (saves every call site from passing it
    twice — once as the FK column, once for the JSONB filter path)."""
    out = dict(base)
    if organisation_id is not None and "org_id" not in out:
        out["org_id"] = str(organisation_id)
    if extra:
        out.update(extra)
    return out


async def record(
    db: AsyncSession,
    *,
    action: AuditAction,
    entity_type: str,
    entity_id: UUID,
    diff: dict[str, Any],
    actor: CurrentActor | None = None,
    organisation_id: UUID | None = None,
    intent_hash: str | None = None,
    intent_metadata: dict[str, Any] | None = None,
    extra_redact: Iterable[str] | None = None,
    flush: bool = False,
) -> AuditLog:
    """Append one row to `audit_log` inside the caller's open transaction.

    `actor`, `intent_hash`, and base `intent_metadata` default to the request
    contextvars set by `AuditContextMiddleware`. `intent_metadata` passed by
    the caller is merged onto the request defaults — e.g. the org-create
    service can stamp `{"project_id": ...}` and the request's IP / UA / path
    survive untouched. `org_id` is auto-stamped from `organisation_id`, so
    callers don't need to pass it twice.

    `flush=True` round-trips to the DB immediately so the inserted row's
    autogenerated PK is available; default `False` lets the row ride the
    next flush in the caller's transaction. Most callers don't need the
    return value, so the default avoids an extra round-trip per audit row.
    """
    where = f"record({entity_type}/{action})"
    resolved_actor = _resolve_actor(actor, where=where)
    resolved_hash, base_metadata = _resolve_intent(intent_hash, where=where)
    metadata = _build_metadata(
        base_metadata, extra=intent_metadata, organisation_id=organisation_id
    )

    row = AuditLog(
        actor_id=resolved_actor.actor_id,
        actor_type=str(resolved_actor.actor_type),
        parent_actor_id=resolved_actor.parent_actor_id,
        organisation_id=organisation_id,
        intent_hash=resolved_hash,
        entity_type=entity_type,
        entity_id=entity_id,
        action=action,
        diff=redact(diff, extra=extra_redact),
        intent_metadata=metadata,
    )
    db.add(row)
    if flush:
        await db.flush()
    return row


def _record_via_connection(
    connection: Any,
    *,
    action: AuditAction,
    entity_type: str,
    entity_id: UUID,
    diff: dict[str, Any],
    actor: CurrentActor,
    organisation_id: UUID | None,
    intent_hash: str,
    intent_metadata: dict[str, Any],
    extra_redact: Iterable[str] | None = None,
) -> None:
    """Synchronous INSERT used by `AuditedModel` mapper-event listeners.

    Mapper events fire synchronously inside the flush. Even on an async
    engine, the callback runs in the greenlet adapter — the `connection`
    argument is a sync `Connection` (or its greenlet-wrapped equivalent),
    so `connection.execute(...)` is a plain blocking call. An `async def`
    here would make this an unawaited coroutine inside the sync hook and
    silently emit zero rows.
    """
    metadata = _build_metadata(
        intent_metadata, extra=None, organisation_id=organisation_id
    )
    connection.execute(
        text(
            "INSERT INTO audit_log "
            "(actor_id, actor_type, parent_actor_id, organisation_id, "
            "intent_hash, entity_type, entity_id, action, diff, intent_metadata) "
            "VALUES (:actor_id, :actor_type, :parent_actor_id, :organisation_id, "
            ":intent_hash, :entity_type, :entity_id, :action, "
            "CAST(:diff AS jsonb), CAST(:intent_metadata AS jsonb))"
        ),
        {
            "actor_id": str(actor.actor_id),
            "actor_type": str(actor.actor_type),
            "parent_actor_id": (
                str(actor.parent_actor_id) if actor.parent_actor_id else None
            ),
            "organisation_id": (
                str(organisation_id) if organisation_id is not None else None
            ),
            "intent_hash": intent_hash,
            "entity_type": entity_type,
            "entity_id": str(entity_id),
            "action": action,
            "diff": json.dumps(redact(diff, extra=extra_redact), default=str),
            "intent_metadata": json.dumps(metadata, default=str),
        },
    )
