import { RouterProvider, createRouter } from "@tanstack/react-router";
import React from "react";
import ReactDOM from "react-dom/client";

import "@/styles/theme.css";
import { useAuthStore } from "@/features/auth/lib/authStore";

// Generated by @tanstack/router-plugin during build / dev.
import { routeTree } from "./routeTree.gen";

const router = createRouter({ routeTree });

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

// Expose the auth store and router in development so Playwright e2e specs can
// drive auth state and SPA navigation without depending on the email +
// register + verify flow (covered exhaustively by backend integration tests).
// DEV-only: vite build sets import.meta.env.DEV = false in production.
if (import.meta.env.DEV) {
  (window as unknown as { __authStore?: typeof useAuthStore }).__authStore = useAuthStore;
  (window as unknown as { __router?: typeof router }).__router = router;
}

const root = document.getElementById("root");
if (!root) throw new Error("Root element not found");

ReactDOM.createRoot(root).render(
  <React.StrictMode>
    <RouterProvider router={router} />
  </React.StrictMode>,
);
