/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgsIndexRouteImport } from './routes/orgs/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OrgsNewRouteImport } from './routes/orgs/new'
import { Route as OrgsSlugRouteImport } from './routes/orgs/$slug'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminOrgsRouteImport } from './routes/admin.orgs'
import { Route as AdminOauthRouteImport } from './routes/admin.oauth'
import { Route as AdminMetricsRouteImport } from './routes/admin.metrics'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminDesignSystemRouteImport } from './routes/admin.design-system'
import { Route as AdminAuthRouteImport } from './routes/admin.auth'
import { Route as OrgsSlugIndexRouteImport } from './routes/orgs/$slug.index'
import { Route as OrgsAcceptShareTokenRouteImport } from './routes/orgs/accept-share.$token'
import { Route as OrgsAcceptInviteTokenRouteImport } from './routes/orgs/accept-invite.$token'
import { Route as OrgsSlugSettingsRouteImport } from './routes/orgs/$slug.settings'
import { Route as AuthVerifyEmailTokenRouteImport } from './routes/auth/verify-email.$token'
import { Route as AuthResetPasswordTokenRouteImport } from './routes/auth/reset-password.$token'
import { Route as AuthMagicLinkTokenRouteImport } from './routes/auth/magic-link.$token'
import { Route as OrgsSlugProjectsIndexRouteImport } from './routes/orgs/$slug.projects.index'
import { Route as OrgsSlugSettingsMembersRouteImport } from './routes/orgs/$slug.settings.members'
import { Route as OrgsSlugSettingsBrandingRouteImport } from './routes/orgs/$slug.settings.branding'
import { Route as OrgsSlugProjectsProjectSlugRouteImport } from './routes/orgs/$slug.projects.$projectSlug'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsIndexRoute = OrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OrgsNewRoute = OrgsNewRouteImport.update({
  id: '/orgs/new',
  path: '/orgs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsSlugRoute = OrgsSlugRouteImport.update({
  id: '/orgs/$slug',
  path: '/orgs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrgsRoute = AdminOrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOauthRoute = AdminOauthRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMetricsRoute = AdminMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDesignSystemRoute = AdminDesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AdminRoute,
} as any)
const OrgsSlugIndexRoute = OrgsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgsSlugRoute,
} as any)
const OrgsAcceptShareTokenRoute = OrgsAcceptShareTokenRouteImport.update({
  id: '/orgs/accept-share/$token',
  path: '/orgs/accept-share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsAcceptInviteTokenRoute = OrgsAcceptInviteTokenRouteImport.update({
  id: '/orgs/accept-invite/$token',
  path: '/orgs/accept-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsSlugSettingsRoute = OrgsSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgsSlugRoute,
} as any)
const AuthVerifyEmailTokenRoute = AuthVerifyEmailTokenRouteImport.update({
  id: '/auth/verify-email/$token',
  path: '/auth/verify-email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordTokenRoute = AuthResetPasswordTokenRouteImport.update({
  id: '/auth/reset-password/$token',
  path: '/auth/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMagicLinkTokenRoute = AuthMagicLinkTokenRouteImport.update({
  id: '/auth/magic-link/$token',
  path: '/auth/magic-link/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsSlugProjectsIndexRoute = OrgsSlugProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => OrgsSlugRoute,
} as any)
const OrgsSlugSettingsMembersRoute = OrgsSlugSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => OrgsSlugSettingsRoute,
} as any)
const OrgsSlugSettingsBrandingRoute =
  OrgsSlugSettingsBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => OrgsSlugSettingsRoute,
  } as any)
const OrgsSlugProjectsProjectSlugRoute =
  OrgsSlugProjectsProjectSlugRouteImport.update({
    id: '/projects/$projectSlug',
    path: '/projects/$projectSlug',
    getParentRoute: () => OrgsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/auth': typeof AdminAuthRoute
  '/admin/design-system': typeof AdminDesignSystemRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/oauth': typeof AdminOauthRoute
  '/admin/orgs': typeof AdminOrgsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/orgs/$slug': typeof OrgsSlugRouteWithChildren
  '/orgs/new': typeof OrgsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/orgs/': typeof OrgsIndexRoute
  '/auth/magic-link/$token': typeof AuthMagicLinkTokenRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/auth/verify-email/$token': typeof AuthVerifyEmailTokenRoute
  '/orgs/$slug/settings': typeof OrgsSlugSettingsRouteWithChildren
  '/orgs/accept-invite/$token': typeof OrgsAcceptInviteTokenRoute
  '/orgs/accept-share/$token': typeof OrgsAcceptShareTokenRoute
  '/orgs/$slug/': typeof OrgsSlugIndexRoute
  '/orgs/$slug/projects/$projectSlug': typeof OrgsSlugProjectsProjectSlugRoute
  '/orgs/$slug/settings/branding': typeof OrgsSlugSettingsBrandingRoute
  '/orgs/$slug/settings/members': typeof OrgsSlugSettingsMembersRoute
  '/orgs/$slug/projects/': typeof OrgsSlugProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/auth': typeof AdminAuthRoute
  '/admin/design-system': typeof AdminDesignSystemRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/oauth': typeof AdminOauthRoute
  '/admin/orgs': typeof AdminOrgsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/orgs/new': typeof OrgsNewRoute
  '/admin': typeof AdminIndexRoute
  '/orgs': typeof OrgsIndexRoute
  '/auth/magic-link/$token': typeof AuthMagicLinkTokenRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/auth/verify-email/$token': typeof AuthVerifyEmailTokenRoute
  '/orgs/$slug/settings': typeof OrgsSlugSettingsRouteWithChildren
  '/orgs/accept-invite/$token': typeof OrgsAcceptInviteTokenRoute
  '/orgs/accept-share/$token': typeof OrgsAcceptShareTokenRoute
  '/orgs/$slug': typeof OrgsSlugIndexRoute
  '/orgs/$slug/projects/$projectSlug': typeof OrgsSlugProjectsProjectSlugRoute
  '/orgs/$slug/settings/branding': typeof OrgsSlugSettingsBrandingRoute
  '/orgs/$slug/settings/members': typeof OrgsSlugSettingsMembersRoute
  '/orgs/$slug/projects': typeof OrgsSlugProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/auth': typeof AdminAuthRoute
  '/admin/design-system': typeof AdminDesignSystemRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/oauth': typeof AdminOauthRoute
  '/admin/orgs': typeof AdminOrgsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/orgs/$slug': typeof OrgsSlugRouteWithChildren
  '/orgs/new': typeof OrgsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/orgs/': typeof OrgsIndexRoute
  '/auth/magic-link/$token': typeof AuthMagicLinkTokenRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/auth/verify-email/$token': typeof AuthVerifyEmailTokenRoute
  '/orgs/$slug/settings': typeof OrgsSlugSettingsRouteWithChildren
  '/orgs/accept-invite/$token': typeof OrgsAcceptInviteTokenRoute
  '/orgs/accept-share/$token': typeof OrgsAcceptShareTokenRoute
  '/orgs/$slug/': typeof OrgsSlugIndexRoute
  '/orgs/$slug/projects/$projectSlug': typeof OrgsSlugProjectsProjectSlugRoute
  '/orgs/$slug/settings/branding': typeof OrgsSlugSettingsBrandingRoute
  '/orgs/$slug/settings/members': typeof OrgsSlugSettingsMembersRoute
  '/orgs/$slug/projects/': typeof OrgsSlugProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/auth'
    | '/admin/design-system'
    | '/admin/health'
    | '/admin/metrics'
    | '/admin/oauth'
    | '/admin/orgs'
    | '/auth/login'
    | '/auth/register'
    | '/orgs/$slug'
    | '/orgs/new'
    | '/admin/'
    | '/orgs/'
    | '/auth/magic-link/$token'
    | '/auth/reset-password/$token'
    | '/auth/verify-email/$token'
    | '/orgs/$slug/settings'
    | '/orgs/accept-invite/$token'
    | '/orgs/accept-share/$token'
    | '/orgs/$slug/'
    | '/orgs/$slug/projects/$projectSlug'
    | '/orgs/$slug/settings/branding'
    | '/orgs/$slug/settings/members'
    | '/orgs/$slug/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/auth'
    | '/admin/design-system'
    | '/admin/health'
    | '/admin/metrics'
    | '/admin/oauth'
    | '/admin/orgs'
    | '/auth/login'
    | '/auth/register'
    | '/orgs/new'
    | '/admin'
    | '/orgs'
    | '/auth/magic-link/$token'
    | '/auth/reset-password/$token'
    | '/auth/verify-email/$token'
    | '/orgs/$slug/settings'
    | '/orgs/accept-invite/$token'
    | '/orgs/accept-share/$token'
    | '/orgs/$slug'
    | '/orgs/$slug/projects/$projectSlug'
    | '/orgs/$slug/settings/branding'
    | '/orgs/$slug/settings/members'
    | '/orgs/$slug/projects'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/auth'
    | '/admin/design-system'
    | '/admin/health'
    | '/admin/metrics'
    | '/admin/oauth'
    | '/admin/orgs'
    | '/auth/login'
    | '/auth/register'
    | '/orgs/$slug'
    | '/orgs/new'
    | '/admin/'
    | '/orgs/'
    | '/auth/magic-link/$token'
    | '/auth/reset-password/$token'
    | '/auth/verify-email/$token'
    | '/orgs/$slug/settings'
    | '/orgs/accept-invite/$token'
    | '/orgs/accept-share/$token'
    | '/orgs/$slug/'
    | '/orgs/$slug/projects/$projectSlug'
    | '/orgs/$slug/settings/branding'
    | '/orgs/$slug/settings/members'
    | '/orgs/$slug/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  OrgsSlugRoute: typeof OrgsSlugRouteWithChildren
  OrgsNewRoute: typeof OrgsNewRoute
  OrgsIndexRoute: typeof OrgsIndexRoute
  AuthMagicLinkTokenRoute: typeof AuthMagicLinkTokenRoute
  AuthResetPasswordTokenRoute: typeof AuthResetPasswordTokenRoute
  AuthVerifyEmailTokenRoute: typeof AuthVerifyEmailTokenRoute
  OrgsAcceptInviteTokenRoute: typeof OrgsAcceptInviteTokenRoute
  OrgsAcceptShareTokenRoute: typeof OrgsAcceptShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/': {
      id: '/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof OrgsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/orgs/new': {
      id: '/orgs/new'
      path: '/orgs/new'
      fullPath: '/orgs/new'
      preLoaderRoute: typeof OrgsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$slug': {
      id: '/orgs/$slug'
      path: '/orgs/$slug'
      fullPath: '/orgs/$slug'
      preLoaderRoute: typeof OrgsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orgs': {
      id: '/admin/orgs'
      path: '/orgs'
      fullPath: '/admin/orgs'
      preLoaderRoute: typeof AdminOrgsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/oauth': {
      id: '/admin/oauth'
      path: '/oauth'
      fullPath: '/admin/oauth'
      preLoaderRoute: typeof AdminOauthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/metrics': {
      id: '/admin/metrics'
      path: '/metrics'
      fullPath: '/admin/metrics'
      preLoaderRoute: typeof AdminMetricsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/design-system': {
      id: '/admin/design-system'
      path: '/design-system'
      fullPath: '/admin/design-system'
      preLoaderRoute: typeof AdminDesignSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auth': {
      id: '/admin/auth'
      path: '/auth'
      fullPath: '/admin/auth'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/orgs/$slug/': {
      id: '/orgs/$slug/'
      path: '/'
      fullPath: '/orgs/$slug/'
      preLoaderRoute: typeof OrgsSlugIndexRouteImport
      parentRoute: typeof OrgsSlugRoute
    }
    '/orgs/accept-share/$token': {
      id: '/orgs/accept-share/$token'
      path: '/orgs/accept-share/$token'
      fullPath: '/orgs/accept-share/$token'
      preLoaderRoute: typeof OrgsAcceptShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/accept-invite/$token': {
      id: '/orgs/accept-invite/$token'
      path: '/orgs/accept-invite/$token'
      fullPath: '/orgs/accept-invite/$token'
      preLoaderRoute: typeof OrgsAcceptInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$slug/settings': {
      id: '/orgs/$slug/settings'
      path: '/settings'
      fullPath: '/orgs/$slug/settings'
      preLoaderRoute: typeof OrgsSlugSettingsRouteImport
      parentRoute: typeof OrgsSlugRoute
    }
    '/auth/verify-email/$token': {
      id: '/auth/verify-email/$token'
      path: '/auth/verify-email/$token'
      fullPath: '/auth/verify-email/$token'
      preLoaderRoute: typeof AuthVerifyEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/$token': {
      id: '/auth/reset-password/$token'
      path: '/auth/reset-password/$token'
      fullPath: '/auth/reset-password/$token'
      preLoaderRoute: typeof AuthResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/magic-link/$token': {
      id: '/auth/magic-link/$token'
      path: '/auth/magic-link/$token'
      fullPath: '/auth/magic-link/$token'
      preLoaderRoute: typeof AuthMagicLinkTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$slug/projects/': {
      id: '/orgs/$slug/projects/'
      path: '/projects'
      fullPath: '/orgs/$slug/projects/'
      preLoaderRoute: typeof OrgsSlugProjectsIndexRouteImport
      parentRoute: typeof OrgsSlugRoute
    }
    '/orgs/$slug/settings/members': {
      id: '/orgs/$slug/settings/members'
      path: '/members'
      fullPath: '/orgs/$slug/settings/members'
      preLoaderRoute: typeof OrgsSlugSettingsMembersRouteImport
      parentRoute: typeof OrgsSlugSettingsRoute
    }
    '/orgs/$slug/settings/branding': {
      id: '/orgs/$slug/settings/branding'
      path: '/branding'
      fullPath: '/orgs/$slug/settings/branding'
      preLoaderRoute: typeof OrgsSlugSettingsBrandingRouteImport
      parentRoute: typeof OrgsSlugSettingsRoute
    }
    '/orgs/$slug/projects/$projectSlug': {
      id: '/orgs/$slug/projects/$projectSlug'
      path: '/projects/$projectSlug'
      fullPath: '/orgs/$slug/projects/$projectSlug'
      preLoaderRoute: typeof OrgsSlugProjectsProjectSlugRouteImport
      parentRoute: typeof OrgsSlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuthRoute: typeof AdminAuthRoute
  AdminDesignSystemRoute: typeof AdminDesignSystemRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminMetricsRoute: typeof AdminMetricsRoute
  AdminOauthRoute: typeof AdminOauthRoute
  AdminOrgsRoute: typeof AdminOrgsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuthRoute: AdminAuthRoute,
  AdminDesignSystemRoute: AdminDesignSystemRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminMetricsRoute: AdminMetricsRoute,
  AdminOauthRoute: AdminOauthRoute,
  AdminOrgsRoute: AdminOrgsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OrgsSlugSettingsRouteChildren {
  OrgsSlugSettingsBrandingRoute: typeof OrgsSlugSettingsBrandingRoute
  OrgsSlugSettingsMembersRoute: typeof OrgsSlugSettingsMembersRoute
}

const OrgsSlugSettingsRouteChildren: OrgsSlugSettingsRouteChildren = {
  OrgsSlugSettingsBrandingRoute: OrgsSlugSettingsBrandingRoute,
  OrgsSlugSettingsMembersRoute: OrgsSlugSettingsMembersRoute,
}

const OrgsSlugSettingsRouteWithChildren =
  OrgsSlugSettingsRoute._addFileChildren(OrgsSlugSettingsRouteChildren)

interface OrgsSlugRouteChildren {
  OrgsSlugSettingsRoute: typeof OrgsSlugSettingsRouteWithChildren
  OrgsSlugIndexRoute: typeof OrgsSlugIndexRoute
  OrgsSlugProjectsProjectSlugRoute: typeof OrgsSlugProjectsProjectSlugRoute
  OrgsSlugProjectsIndexRoute: typeof OrgsSlugProjectsIndexRoute
}

const OrgsSlugRouteChildren: OrgsSlugRouteChildren = {
  OrgsSlugSettingsRoute: OrgsSlugSettingsRouteWithChildren,
  OrgsSlugIndexRoute: OrgsSlugIndexRoute,
  OrgsSlugProjectsProjectSlugRoute: OrgsSlugProjectsProjectSlugRoute,
  OrgsSlugProjectsIndexRoute: OrgsSlugProjectsIndexRoute,
}

const OrgsSlugRouteWithChildren = OrgsSlugRoute._addFileChildren(
  OrgsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  OrgsSlugRoute: OrgsSlugRouteWithChildren,
  OrgsNewRoute: OrgsNewRoute,
  OrgsIndexRoute: OrgsIndexRoute,
  AuthMagicLinkTokenRoute: AuthMagicLinkTokenRoute,
  AuthResetPasswordTokenRoute: AuthResetPasswordTokenRoute,
  AuthVerifyEmailTokenRoute: AuthVerifyEmailTokenRoute,
  OrgsAcceptInviteTokenRoute: OrgsAcceptInviteTokenRoute,
  OrgsAcceptShareTokenRoute: OrgsAcceptShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
